### ISSUE TITLE
Question: how to use the typings

### ISSUE THREAD

**Issue by cramhead** [TechnologyAdvice/typings-stardust#1]
I've installed done an `npm i stardust -S` and added the cdn reference to my index page, but my typescript transpiler says "ts: Cannot find module stardust". I found a copy of the typings from https://raw.githubusercontent.com/TechnologyAdvice/typings-stardust/master/stardust.d.ts, tried putting them in typings folder under globals/startdust/index.d.ts, and referred to them in the `typings/index.d.ts` file, but still can't find the typings. Any ideas?

**Comment by dvdzkwsk** [comment]
These are still incomplete, I unfortunately have not had time yet to finish them. Apparently with TS 2.0 they should be able to reside directly in the main Stardust package, which will make this standalone repository obsolete once it is completed and merged there. They _are_ still being worked on, but due to work obligations and the fact that our codebases that use Stardust are not in TypeScript it has not yet been a top priority.

Apologies for any confusion. When the typings are complete I'll be sure to ping you. In the meantime, PR's are welcome :).

**Comment by levithomason** [comment]
@hlehmann @dylankiss @moaead are any of you folks successfully using typescript with Stardust at the moment?

**Comment by dylankiss** [comment]
I am still using my own typings for now, only for the few components I use. Components are still changing frequently, so that is easier to maintain at the moment. I think it would definitely be a good idea to put the typings in the main project. This was already possible pre TS 2.0.

If you would move the typings to the main Stardust repo, I could make a PR with the extra components I am using for now and use these typings instead of my own.

**Comment by levithomason** [comment]
Sounds good.  Seems like we should do this when APIs stabilize.  Thanks for the info and offer.

**Comment by empz** [comment]
Yes, this was already possible pre TS 2.0.

Including the typings in the main stardust repo is just a matter of adding the d.ts file and including some extra lines in package.json. 
Leaving the documentation here for future reference.
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by levithomason** [comment]
@cramhead @dylankiss @emzero Typings are now merged into the main repo.  We'll delete this repo soon.

I would also like to start an `/examples` directory on the main repo that shows minimal full project setup examples, one of those utilizing typings.  If anyone would like to take a stab at that, I'd be thrilled!
